services:
  - type: web
    name: yt-api-backend
    env: python
    buildCommand: |
      bash render-build.sh && pip install -r requirements.txt
    startCommand: |
      PATH=$PATH:$(pwd) python app.py
    envVars:
      - key: YOUTUBE_API_KEY
        value: AIzaSyDHLtCi8bhQ1IiY-SkkaxLXifB4LoUCuLI
