services:
  - type: web
    name: youtube-audio-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: YOUTUBE_API_KEY
        sync: true
