services:
  - type: web
    name: youtube-music-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: YOUTUBE_API_KEY
        value: your-actual-api-key
